add build-maven-project
jenkins-zh/jenkins-zh-courses pull request #3
Opened 2020-03-17 11:37 UTC by donhui

2020-03-17 12:22 UTC, LinuxSuRen commented
可以把你自己测试的地址贴一下。另外，我看到你 git commit 时没有用 GitHub 中配置的邮箱，这样合并后，contributors 里就看不到你的记录。可以调整下。

2020-03-17 12:24 UTC, LinuxSuRen commented on build-maven-project/index.json
> +  "difficulty": "Beginner",
这里是不是也可以使用中文？

2020-03-17 12:28 UTC, donhui commented on build-maven-project/index.json
> +  "difficulty": "Beginner",
修改了

2020-03-17 12:29 UTC, donhui commented
katacoda 教程地址：
https://katacoda.com/donghui/scenarios/build-maven-project

2020-03-17 12:29 UTC, LinuxSuRen requested changes
非常棒，提供了一些反馈
可以把这个教程加入到配置文件  `profile-pathway.json` 中

当前项目的地址 https://github.com/jenkins-zh/jenkins-zh-courses 也可以加到 intro.md 中，这样方便大家来完善或者学习。

2020-03-17 12:29 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +    donhui/jenkins-with-maven:2.204.5`{{execute}}
这里是否可以使用定制版的镜像呢？

2020-03-17 12:29 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +你可以通过下面 URL 加载 Jenkins Dashboard：`https://[[HOST_SUBDOMAIN]]-8080-[[KATACODA_HOST]].environments.katacoda.com/`{{open}}
`加载`->`打开`？

2020-03-17 12:29 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +用户名是：`admin`{{copy}}，密码是：`9YxwvCOUPML8onXF`{{copy}}
`{{copy}}`、`{{execute}}` 等的用法可以统一整理到 readme 里，方便大家查看

2020-03-17 12:29 UTC, LinuxSuRen commented on build-maven-project/step2.md
> +点击`新建任务`或`创建一个新任务`，
上面是 job ，这里是任务，全部统一里会比较好。

2020-03-17 12:29 UTC, LinuxSuRen commented on build-maven-project/step2.md
> +该 Pipeline 下的 `stages` 包括一个 `stage('Build')`，这个 `stage` 的 `steps` 中会从 github 下载代码，然后使用 maven 构建项目，
github -> GitHub

2020-03-17 12:31 UTC, donhui commented on build-maven-project/step1.md
> +    donhui/jenkins-with-maven:2.204.5`{{execute}}
你那个定制镜像，还不太会用。。。

2020-03-17 12:44 UTC, donhui commented on build-maven-project/step2.md
> +点击`新建任务`或`创建一个新任务`，
已修改

2020-03-17 12:45 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +    donhui/jenkins-with-maven:2.204.5`{{execute}}
那周三我们一起过一下，大家集中维护一份的话比较好。

2020-03-17 12:46 UTC, donhui commented on build-maven-project/step1.md
> +    donhui/jenkins-with-maven:2.204.5`{{execute}}
OK

2020-04-01 13:15 UTC, LinuxSuRen commented on build-maven-project/step2.md
> +可以看到脚本区域就被如下 Pipeline 填充：
建议这里让用户直接选择或者拷贝下面的内容

2020-04-01 13:18 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +    -p 8080:8080 -p 50000:50000 \
可以解释下 50000 这个端口的意义

2020-04-02 09:16 UTC, donhui commented on build-maven-project/step1.md
> +    -p 8080:8080 -p 50000:50000 \
下面有说明

2020-04-02 09:18 UTC, LinuxSuRen commented on build-maven-project/step1.md
> +    -p 8080:8080 -p 50000:50000 \
嗯，看到了。

2020-04-02 09:18 UTC, LinuxSuRen approved these changes

2020-04-02 09:37 UTC, merged